### ISSUE TITLE
Example readme does not compile

### ISSUE THREAD

**Issue by Payne325** [jam1garner/gc-adapter#1]
Hi there, I'm currently experimenting with this crate, and I found the example in the Readme does not compile as is. I had to include the `libusb` feature when adding the dependency to my TOML like so:

`gc-adapter = {version = "0.1.2", features = ["libusb"]}`  

Could this information be included in the readme file for future users? Or ideally, can the necessity for the feature definition be removed?

Many Thanks,
Payne325

**Comment by jam1garner** [comment]
Thanks for the heads up! I think for now I don't intend to make libusb a default feature, however I will consider doing so in the future
